name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - run: uv run pyinstaller --name dsm --icon ./static/icon.ico --onefile run.py --add-data "templates:templates" --add-data "static:static" --clean

      - uses: actions/upload-artifact@v4
        with:
          name: dsm
          path: dist/dsm.exe
